name: Ruby

on:
  push:
    branches: master
  pull_request:
    branches: '*'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.5', '2.6', '2.7', '3.0', '3.1']
        redis-version: [5, 6]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies
        run: |
          gem install bundler -v '1.17.3' --no-document
          bundle install --jobs 4 --retry 3

      - name: Run Tests
        run: |
          bundle exec rspec
