name: Ruby

on:
  push:
    branches: master
  pull_request:
    branches: '*'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0', '3.1', '3.2', '3.3']
        redis-version: ['4.0', '5.0', '6.0', '7.0', 'valkey-8.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Redis ${{ matrix.redis-version }}
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies
        run: |
          gem install bundler -v '2.5.7' --no-document
          bundle install --jobs 4 --retry 3

      - name: Run Tests
        run: |
          bundle exec rspec
